-- Throwaway integration fixture for scripts/migrate-legacy.ts.
-- Run only against a disposable PostgreSQL database: it replaces the listed public tables.

create extension if not exists pgcrypto;

drop table if exists public.topic_related_ids;
drop table if exists public.topics;
drop table if exists public.subjects;
drop table if exists public.contact_messages;
drop table if exists public.users;

create table public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  username text not null unique,
  password_hash text not null,
  display_name text not null,
  role text not null,
  reset_token text,
  reset_token_expiry timestamptz,
  created_at timestamptz not null
);

create table public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  color_hex text not null,
  sort_order integer not null
);

-- Hibernate commonly maps @Lob String to an OID. The importer detects this shape.
create table public.topics (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects (id),
  parent_topic_id bigint references public.topics (id),
  title text not null,
  sort_order integer not null,
  preview_snippet text not null,
  content oid not null
);

create table public.topic_related_ids (
  topic_id bigint not null references public.topics (id),
  related_topic_id bigint not null
);

-- This @Lob-shaped field is text, exercising the importer's other supported representation.
create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null
);

insert into public.users
  (id, email, username, password_hash, display_name, role, created_at)
values
  (1, 'student@example.com', 'student_one', crypt('password123', gen_salt('bf')), 'Student One', 'STUDENT', '2026-01-01T00:00:00Z'),
  (2, 'tutor@example.com', 'tutor_one', crypt('password123', gen_salt('bf')), 'Tutor One', 'TUTOR', '2026-01-02T00:00:00Z'),
  (3, 'admin@example.com', 'admin_one', crypt('password123', gen_salt('bf')), 'Admin One', 'ADMIN', '2026-01-03T00:00:00Z');

insert into public.subjects (id, name, color_hex, sort_order)
values (1, 'Fixture Law', '#A9CBA0', 0);

insert into public.topics
  (id, subject_id, parent_topic_id, title, sort_order, preview_snippet, content)
values
  (1, 1, null, 'Parent Topic', 0, 'Parent preview', lo_from_bytea(0, convert_to('Parent content', 'UTF8'))),
  (2, 1, 1, 'Child Topic', 0, 'Child preview', lo_from_bytea(0, convert_to('Child content', 'UTF8'))),
  (3, 1, null, 'Related Topic', 1, 'Related preview', lo_from_bytea(0, convert_to('Related content', 'UTF8')));

insert into public.topic_related_ids (topic_id, related_topic_id)
values (1, 3), (3, 1);

insert into public.contact_messages (id, name, email, message, created_at)
values (1, 'Visitor', 'visitor@example.com', 'Fixture support request', '2026-02-01T00:00:00Z');
