create type public.user_role as enum ('STUDENT', 'TUTOR', 'ADMIN');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username varchar(24) not null,
  normalized_username text generated always as (lower(username)) stored,
  display_name text not null,
  role public.user_role not null default 'STUDENT',
  legacy_user_id bigint unique,
  created_at timestamptz not null default now(),
  constraint profiles_username_length check (char_length(username) between 3 and 24),
  constraint profiles_username_format check (username ~ '^[a-zA-Z0-9_]+$'),
  constraint profiles_normalized_username_unique unique (normalized_username)
);

create table public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  color_hex varchar(7) not null,
  sort_order integer not null,
  constraint subjects_color_hex_format check (color_hex ~ '^#[0-9A-Fa-f]{6}$')
);

create table public.topics (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects (id) on delete cascade,
  parent_topic_id bigint references public.topics (id) on delete cascade,
  title text not null,
  sort_order integer not null,
  preview_snippet varchar(500) not null,
  content text not null,
  constraint topics_not_own_parent check (parent_topic_id is null or parent_topic_id <> id)
);

create table public.topic_related_topics (
  topic_id bigint not null references public.topics (id) on delete cascade,
  related_topic_id bigint not null references public.topics (id) on delete cascade,
  primary key (topic_id, related_topic_id),
  constraint related_topics_not_self check (topic_id <> related_topic_id)
);

create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now(),
  constraint contact_message_length check (char_length(message) between 1 and 4000)
);

create index topics_subject_id_idx on public.topics (subject_id);
create index topics_parent_topic_id_idx on public.topics (parent_topic_id);
create index topics_subject_sort_idx on public.topics (subject_id, sort_order);
create index topic_related_related_id_idx on public.topic_related_topics (related_topic_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    new.raw_user_meta_data ->> 'username',
    new.raw_user_meta_data ->> 'display_name'
  );
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.topics enable row level security;
alter table public.topic_related_topics enable row level security;
alter table public.contact_messages enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.subjects from anon, authenticated;
revoke all on table public.topics from anon, authenticated;
revoke all on table public.topic_related_topics from anon, authenticated;
revoke all on table public.contact_messages from anon, authenticated;

grant select on table public.profiles to authenticated;
grant select on table public.subjects to authenticated;
grant select on table public.topics to authenticated;
grant select on table public.topic_related_topics to authenticated;
grant insert on table public.contact_messages to anon, authenticated;
grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated;

create policy "Users can read their own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Authenticated users can read subjects"
  on public.subjects for select
  to authenticated
  using (true);

create policy "Authenticated users can read topics"
  on public.topics for select
  to authenticated
  using (true);

create policy "Authenticated users can read related topics"
  on public.topic_related_topics for select
  to authenticated
  using (true);

create policy "Anyone can submit a contact message"
  on public.contact_messages for insert
  to anon, authenticated
  with check (
    char_length(trim(name)) > 0
    and char_length(trim(email)) > 0
    and char_length(message) between 1 and 4000
  );
